class RegisterMap {
  const RegisterMap({
    this.unitId = 1,
    this.pointsBase = 0,
    this.slaveStatusBase = 1080,
    this.cmdBase = 1240,
    this.directoryBase = 1264,
    this.cfgBase = 1296,
    this.diagBase = 1376,
    this.topologyBase = 1408,
    this.directoryReadCount = 32,
    this.expectedMapVersion = 4,
    this.expectedPointStride = 6,
    this.expectedMaxPoints = 180,
    this.expectedCmdBlockSize = 24,
    this.expectedStatusBlockSize = 8,
    this.mapVersionReg = 0,
    this.mapFlagsReg = 1,
    this.pointCountReg = 4,
    this.pointStrideReg = 5,
    this.pointsBaseReg = 6,
    this.slaveStatusBaseReg = 7,
    this.cmdBaseReg = 8,
    this.maxPointsReg = 11,
    this.cmdBlockSizeReg = 12,
    this.statusBlockSizeReg = 13,
    this.rtcHourOffset = 14,
    this.rtcMinuteOffset = 15,
    this.rtcSetHourOffset = 16,
    this.rtcSetMinuteOffset = 17,
    this.rtcSetTokenOffset = 18,
    this.rtcSetAppliedTokenOffset = 19,
    this.rtcSetResultOffset = 20,
    this.pointRowStride = 6,
    this.pointValueHiReg = 0,
    this.pointValueLoReg = 1,
    this.pointQualityReg = 2,
    this.pointAgeSecReg = 3,
    this.pointModuleIdReg = 4,
    this.pointFlagsReg = 5,
    this.slaveStatusOnlineFlagMask = 0x0001,
    this.slaveStatusStaleFlagMask = 0x0002,
    this.slaveStatusStatusOffset = 0,
    this.slaveStatusLastOkAgeOffset = 1,
    this.slaveStatusErrTimeoutOffset = 2,
    this.slaveStatusErrCrcOffset = 3,
    this.slaveStatusErrExceptionOffset = 4,
    this.slaveStatusDataVersionOffset = 5,
    this.slaveStatusValidMaskOffset = 6,
    this.slaveStatusOutStateMaskOffset = 7,
    this.cmdTargetSlaveIdOffset = 0,
    this.cmdTargetModuleIdOffset = 1,
    this.cmdProfileIdOffset = 2,
    this.cmdPayloadLenOffset = 3,
    this.cmdPayloadBaseOffset = 4,
    this.cmdTriggerOffset = 20,
    this.cmdLastAppliedTriggerOffset = 21,
    this.cmdResultOffset = 22,
    this.cmdIoErrOffset = 23,
    this.schedulePayloadRegisterCount = 16,
    this.schedulePollingTimeoutMs = 25000,
    this.schedulePollingPeriodMs = 500,
    this.topologySubmitTokenOffset = 0,
    this.topologyResultCodeOffset = 1,
    this.topologyResultTokenOffset = 2,
    this.topologyActiveFlagsOffset = 3,
    this.topologyVersionMajorOffset = 4,
    this.topologyVersionMinorOffset = 5,
    this.topologyGenerationHiOffset = 6,
    this.topologyGenerationLoOffset = 7,
    this.topologySizeHiOffset = 8,
    this.topologySizeLoOffset = 9,
    this.topologyReqChunkIndexOffset = 10,
    this.topologyReqChunkWordsOffset = 11,
    this.topologyReqTotalSizeHiOffset = 12,
    this.topologyReqTotalSizeLoOffset = 13,
    this.topologyReqChunkCrcHiOffset = 14,
    this.topologyReqChunkCrcLoOffset = 15,
    this.topologyReqFlagsOffset = 16,
    this.topologyReqGenerationHiOffset = 17,
    this.topologyReqGenerationLoOffset = 18,
    this.topologyChunkDataOffset = 20,
    this.topologyChunkWordsMax = 120,
    this.topologyResultQueued = 1,
    this.topologyResultApplied = 2,
  });

  final int unitId;
  final int pointsBase;
  final int slaveStatusBase;
  final int cmdBase;
  final int directoryBase;
  final int cfgBase;
  final int diagBase;
  final int topologyBase;

  final int directoryReadCount;
  final int expectedMapVersion;
  final int expectedPointStride;
  final int expectedMaxPoints;
  final int expectedCmdBlockSize;
  final int expectedStatusBlockSize;

  final int mapVersionReg;
  final int mapFlagsReg;
  final int pointCountReg;
  final int pointStrideReg;
  final int pointsBaseReg;
  final int slaveStatusBaseReg;
  final int cmdBaseReg;
  final int maxPointsReg;
  final int cmdBlockSizeReg;
  final int statusBlockSizeReg;
  final int rtcHourOffset;
  final int rtcMinuteOffset;
  final int rtcSetHourOffset;
  final int rtcSetMinuteOffset;
  final int rtcSetTokenOffset;
  final int rtcSetAppliedTokenOffset;
  final int rtcSetResultOffset;

  final int pointRowStride;
  final int pointValueHiReg;
  final int pointValueLoReg;
  final int pointQualityReg;
  final int pointAgeSecReg;
  final int pointModuleIdReg;
  final int pointFlagsReg;

  final int slaveStatusOnlineFlagMask;
  final int slaveStatusStaleFlagMask;
  final int slaveStatusStatusOffset;
  final int slaveStatusLastOkAgeOffset;
  final int slaveStatusErrTimeoutOffset;
  final int slaveStatusErrCrcOffset;
  final int slaveStatusErrExceptionOffset;
  final int slaveStatusDataVersionOffset;
  final int slaveStatusValidMaskOffset;
  final int slaveStatusOutStateMaskOffset;

  final int cmdTargetSlaveIdOffset;
  final int cmdTargetModuleIdOffset;
  final int cmdProfileIdOffset;
  final int cmdPayloadLenOffset;
  final int cmdPayloadBaseOffset;
  final int cmdTriggerOffset;
  final int cmdLastAppliedTriggerOffset;
  final int cmdResultOffset;
  final int cmdIoErrOffset;

  final int schedulePayloadRegisterCount;
  final int schedulePollingTimeoutMs;
  final int schedulePollingPeriodMs;

  final int topologySubmitTokenOffset;
  final int topologyResultCodeOffset;
  final int topologyResultTokenOffset;
  final int topologyActiveFlagsOffset;
  final int topologyVersionMajorOffset;
  final int topologyVersionMinorOffset;
  final int topologyGenerationHiOffset;
  final int topologyGenerationLoOffset;
  final int topologySizeHiOffset;
  final int topologySizeLoOffset;
  final int topologyReqChunkIndexOffset;
  final int topologyReqChunkWordsOffset;
  final int topologyReqTotalSizeHiOffset;
  final int topologyReqTotalSizeLoOffset;
  final int topologyReqChunkCrcHiOffset;
  final int topologyReqChunkCrcLoOffset;
  final int topologyReqFlagsOffset;
  final int topologyReqGenerationHiOffset;
  final int topologyReqGenerationLoOffset;
  final int topologyChunkDataOffset;
  final int topologyChunkWordsMax;
  final int topologyResultQueued;
  final int topologyResultApplied;

  static const RegisterMap assumed = RegisterMap();
}
